---
Name: workflowconfig
---
SilverStripe\Core\Injector\Injector:
  DNADesign\Workflow\Extensions\WorkflowApplicable:
    class: DNADesign\Workflow\Extensions\WorkflowApplicable
    type: prototype

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - DNADesign\Workflow\Extensions\WorkflowApplicable
SilverStripe\CMS\Controllers\CMSPageEditController:
  extensions:
    - DNADesign\Workflow\Extensions\AdvancedWorkflowExtension
SilverStripe\Forms\GridField\GridFieldDetailForm_ItemRequest:
  extensions:
    - DNADesign\Workflow\Extensions\AdvancedWorkflowExtension
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - dnadesign/silverstripe-workflow:client/dist/styles/advancedworkflow.css
